const paginatePaths = [
  [
    'https://www.jib.co.th/web/pcsetspec/load_product/vga/0/?qty=0',
    'https://www.jib.co.th/web/pcsetspec/load_product/vga/0/80/?qty=0',
    'https://www.jib.co.th/web/pcsetspec/load_product/vga/0/160/?qty=0',
    'https://www.jib.co.th/web/pcsetspec/load_product/vga/0/240/?qty=0',
  ],
  [
    'https://www.jib.co.th/web/pcsetspec/load_product/cpucooler/0/?qty=0',
    'https://www.jib.co.th/web/pcsetspec/load_product/cpucooler/0/80/?qty=0',
  ],
  [
    'https://www.jib.co.th/web/pcsetspec/load_product/powersupply/0/?qty=0',
    'https://www.jib.co.th/web/pcsetspec/load_product/powersupply/0/80/?qty=0',
  ],
  [
    'https://www.jib.co.th/web/pcsetspec/load_product/cpuliquid/0/?qty=0',
    'https://www.jib.co.th/web/pcsetspec/load_product/cpuliquid/0/80/?qty=0',
  ],
  [
    'https://www.jib.co.th/web/pcsetspec/load_product/pccase/0/?qty=0',
    'https://www.jib.co.th/web/pcsetspec/load_product/pccase/0/80/?qty=0',
    'https://www.jib.co.th/web/pcsetspec/load_product/pccase/0/160/?qty=0',
    'https://www.jib.co.th/web/pcsetspec/load_product/pccase/0/240/?qty=0',
  ],
  [
    'https://www.jib.co.th/web/pcsetspec/load_product/ram/0/?qty=0',
    'https://www.jib.co.th/web/pcsetspec/load_product/ram/0/80/?qty=0',
    'https://www.jib.co.th/web/pcsetspec/load_product/ram/0/160/?qty=0',
  ],
  [
    'https://www.jib.co.th/web/pcsetspec/load_product/mouse/0/?qty=0',
    'https://www.jib.co.th/web/pcsetspec/load_product/mouse/0/80/?qty=0',
    'https://www.jib.co.th/web/pcsetspec/load_product/mouse/0/160/?qty=0',
    'https://www.jib.co.th/web/pcsetspec/load_product/mouse/0/240/?qty=0',
  ],
  [
    'https://www.jib.co.th/web/pcsetspec/load_product/keyboard/0/?qty=0',
    'https://www.jib.co.th/web/pcsetspec/load_product/keyboard/0/80/?qty=0',
    'https://www.jib.co.th/web/pcsetspec/load_product/keyboard/0/160/?qty=0',
    'https://www.jib.co.th/web/pcsetspec/load_product/keyboard/0/240/?qty=0',
  ],
  [
    'https://www.jib.co.th/web/pcsetspec/load_product/monitor/0/?qty=0',
    'https://www.jib.co.th/web/pcsetspec/load_product/monitor/0/80/?qty=0',
    'https://www.jib.co.th/web/pcsetspec/load_product/monitor/0/160/?qty=0',
    'https://www.jib.co.th/web/pcsetspec/load_product/monitor/0/240/?qty=0',
  ],
  [
    'https://www.jib.co.th/web/pcsetspec/load_product/m2/0/?qty=0',
    'https://www.jib.co.th/web/pcsetspec/load_product/m2/0/80/?qty=0',
  ],
  [
    'https://www.jib.co.th/web/pcsetspec/load_product/mainboard/0/?qty=0',
    'https://www.jib.co.th/web/pcsetspec/load_product/mainboard/0/80/?qty=0',
    'https://www.jib.co.th/web/pcsetspec/load_product/mainboard/0/160/?qty=0',
    'https://www.jib.co.th/web/pcsetspec/load_product/mainboard/0/240/?qty=0',
  ],
  ['https://www.jib.co.th/web/pcsetspec/load_product/harddisk/0/?qty=0'],
  ['https://www.jib.co.th/web/pcsetspec/load_product/ssd/0/?qty=0'],
  ['https://www.jib.co.th/web/pcsetspec/load_product/cpu/0/?qty=0'],
];
